###############################################
## common配置
###############################################
spring:
  profiles:
    active: development
  application:
    name: springbootlearn-userservice
  data:
    redis:
      repositories:
        enabled: false
    elasticsearch:
      repositories:
        enabled: false
  cloud:
    loadbalancer:
      retry:
        enabled: false
    inetutils:
      ignoredInterfaces:
      - docker0
      - veth.*
server:
  port: 9090
  type: provider
###############################################
## apollo配置
###############################################
app:
  id: java_spring_boot_learn_api
apollo:
  bootstrap:
    enabled: true
  cacheDir: /data/apollo-cache
  meta: http://localhost:8080
###############################################
## eureka配置
##############################################
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5