apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sewing-api-deployment
  labels:
    app: sewing-api-deployment
spec:
  replicas: 1
  template:
    spec:
      volumes:
      - name: config
        configMap:
          name: application-file-api
          items:
          - key: application.properties
            path: application.properties
          - key: application-development.properties
            path: application-development.properties
          - key: application-test.properties
            path: application-test.properties
          - key: application-product.properties
            path: application-product.properties
      containers:
      - name: sewing-api
        livenessProbe:
          httpGet:
            path: /health
            port: 20001
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 20001
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /maven/config
          name: config