###############################################
## common配置
###############################################
spring:
  profiles:
    active: development
  application:
    name: springbootlearn-notifyservice
  zipkin:
    base-url: http://localhost:9411
    service.name: springbootlearn-notifyservice
    sender.type: web
  sleuth:
    sampler:
      probability: 1.0
      rate: 50
    traceId128: true
    web:
      client:
        enabled: true
    enabled: true
  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /static/*
  webflux:
    static-path-pattern: /static/*
server:
  port: 8101
###############################################
## apollo配置
###############################################
app:
  id: java_spring_boot_learn_api
apollo:
  bootstrap:
    enabled: true
  cacheDir: /data/apollo-cache
  meta: http://localhost:8080
###############################################
## eureka配置
##############################################
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5