###############################################
## common配置
###############################################
spring:
  profiles:
    active: development
  application:
    name: springbootlearn-gateway
  sleuth:
    sampler:
      probability: 1.0
    traceId128: true
server:
  port: 7080
###############################################
## apollo配置
###############################################
app:
  id: java_spring_boot_learn_api
apollo:
  bootstrap:
    enabled: true
  cacheDir: /data/apollo-cache
  meta: http://localhost:8080

