apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: penghuiping/notify-microservice
      jib: {}

deploy:
  kustomize:
    path: kustomize/base

profiles:
  - name: dev
    deploy:
      kustomize:
        path: kustomize/dev