apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: userservice
  name: userservice
spec:
  ports:
  - name: 8102-8102
    port: 8102
    protocol: TCP
    targetPort: 8102
  selector:
    app: userservice
  type: ClusterIP
status:
  loadBalancer: {}

