apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mediaservice
  name: mediaservice
spec:
  ports:
  - name: 8100-8100
    port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: mediaservice
  type: ClusterIP
status:
  loadBalancer: {}

