###############################################
## common配置
###############################################
spring:
  main.allow-bean-definition-overriding: true
  profiles:
    active: development
  application:
    name: springbootlearn-h5api
  zipkin:
    base-url: http://localhost:9411
    service.name: springbootlearn-h5api
    sender.type: web
    sleuth:
      sampler:
        probability: 1.0
      traceId128: true
      web:
        client:
          enabled: true
  cloud:
    loadbalancer:
      retry:
        enabled: false
    inetutils:
      ignoredInterfaces:
      - docker0
      - veth.*
server:
  port: 8082
###############################################
## apollo配置
###############################################
app:
  id: java_spring_boot_learn_api
apollo:
  bootstrap:
    enabled: true
  cacheDir: /data/apollo-cache
  meta: http://localhost:8080
###############################################
## eureka配置
##############################################
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5