########################################################
###common
########################################################
app:
  rabbitmq:
    ip: ${rabbitmq_ip}
    port: ${rabbitmq_port}
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}
    virtualHost: ${rabbitmq_virtualHost}
  redis:
    host: ${redis_host}
    port: ${redis_port}
    nodes: ${redis_nodes}
    password: ${redis_password}
    database: ${redis_database}
  filesever:
    host: ${fileServer_host}
    path: ${fileServer_path}
########################################################
### static resources and upload load file
########################################################
base_assets_url: http://${app.filesever.host}/${spring.application.name}/assets/
base_assets_upload_path: ${app.filesever.path}/${spring.application.name}/upload/
base_assets_upload_url: http://${app.filesever.host}/${spring.application.name}/upload/
########################################################
### LOG
########################################################
logging:
  file: logs/h5api.log
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.php25: INFO
spring:
  ########################################################
  ### spring cloud stream
  ########################################################
  cloud:
    stream:
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${app.rabbitmq.ip}
                port: ${app.rabbitmq.port}
                username: ${app.rabbitmq.username}
                password: ${app.rabbitmq.password}
                virtual-host: ${app.rabbitmq.virtualHost}
      bindings:
        input:
          destination: data-exchange
          contentType: application/json
          binder: local_rabbit
          consumer:
            auto-bind-dlq: true
            republish-to-dlq: true
            max-attempts: 3
        output:
          destination: data-exchange
          contentType: application/json
          binder: local_rabbit
  ########################################################
  ### redis
  ########################################################
  redis:
    host: ${app.redis.host}
    port: ${app.redis.port}
    database: ${app.redis.database}
    ssl: false
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1s
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1s
        min-idle: 0
    timeout: 0s
  #    cluster:
  #      max-redirects: 3
  #      nodes: 10.186.123.159:7380,10.186.123.159:7381,10.186.123.188:7380
  #    sentinel:
  #      master: master
  #      nodes: 10.182.175.63:26380,10.182.175.64:26380
  #    password: ${app.redis.password}
  ########################################################
  ### fileupload
  ########################################################
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 1000Mb








